name: PHP FTP Deployment

on:
  push:
    branches:
      - main  # You can change this to any branch you wish to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Specify the PHP version you need

    - name: Install Composer dependencies
      run: |
        curl -sS https://getcomposer.org/installer | php
        php composer.phar install --no-dev --optimize-autoloader  # Install dependencies
        
    - name: Build/Prepare PHP Project (Optional)
      run: |
        # You can include additional steps here if needed to build your project
        # For example, compiling assets or other tasks
        echo "Nothing to build"  # Remove or modify based on your needs

    - name: Install lftp (FTP client)
      run: sudo apt-get install -y lftp

    - name: Deploy to FTP with Debug Logs and Ignore SSL Cert
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        TARGET_DIR="public_html"  # The directory on the FTP server
        LOCAL_DIR="."  # Local directory to upload, typically your project root after Composer install
        # Full command to ignore SSL certificates, force FTP, and debug logs
        lftp -c "
          set -a;  # Show all variables (for debugging purposes)
          set net:debug 1;  # Enable debugging (set to 2 or 3 for more verbosity)
          set ftp:ssl-force no;  # Force plain FTP (don't use SSL)
          set ftp:ssl-verify-certificate no;  # Skip SSL certificate verification
          set ssl:check-certificate no;  # Ignore SSL certificate verification
          set ssl:check-hostname no;  # Disable host verification (useful for self-signed certs)
          set net:reconnect-interval-base 5;  # Reconnect interval for failures
          set net:max-retries 3;  # Maximum retries on failure
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
          mirror -R $LOCAL_DIR $TARGET_DIR --ignore-time --only-newer --verbose;
        "
