name: Deploy and Validate PHP Code

on:
  push:
    branches:
      - main  # Trigger on push to the main branch (after merge)

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP and install required dependencies
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Adjust PHP version as required

      # Install Composer dependencies (optional, adjust if using Composer)
      - name: Install Composer dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install --no-interaction

      # Validate PHP code (Linting)
      #- name: Validate PHP code
        #run: |
          #find . -type f -name "*.php" -exec php -l {} \;

      # Configure FTP Connection
      - name: Install ncftp
        run: sudo apt-get install -y ncftp

      # Set FTP credentials
      - name: Set FTP credentials
        run: |
          echo "open ${FTP_SERVER}" > ncftp_cmd.txt
          echo "user ${FTP_USERNAME} ${FTP_PASSWORD}" >> ncftp_cmd.txt
          echo "cd /public_html" >> ncftp_cmd.txt  # Update this to the correct directory
          echo "quit" >> ncftp_cmd.txt

      # Prepare files for upload, respecting .gitignore
      - name: Prepare files for upload (ignore gitignored files)
        run: |
          # Get list of files tracked by git (ignoring .gitignore files)
          git ls-files --exclude-standard | tar -czf files_to_upload.tar.gz -T -

      # Upload files via FTP using ncftp, ignoring SSL certificate validation
      - name: Upload files to FTP server
        run: |
          # Extract the files and upload via lftp
          mkdir -p /tmp/uploaded_files
          tar -xzf files_to_upload.tar.gz -C /tmp/uploaded_files
          lftp -c "set ssl:verify-certificate no; open -u ${FTP_USERNAME},${FTP_PASSWORD} ${FTP_SERVER}; cd /public_html; mirror -R /tmp/uploaded_files /public_html; bye"
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
